server:
  port: 8070

spring:
  application:
    name: ${artifactId}
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/NuLiing/spring-cloud-config-test.git
      label: master #读取分支
  security: #配置身份验证
    user:
      name: sample #账号
      password: sample123 #密码

encrypt:
  key: cntest

eureka:
  client:
    service-url:
      defaultZone: http://sample:sample123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
