server:
  port: 10092

spring:
  application:
    name: ${artifactId}
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output1:
            producer:
              group: test-group1
          output2:
            producer:
              group: test-group2
      bindings:
        output1:
          destination: test-topic1
          content-type: application/json
        output2:
          destination: test-topic2
          content-type: application/json
