server:
  port: 10091

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: cloud-user-service-dubbo
  consumer:
    check: false

spring:
  application:
    # Dubbo 应用名称
    name: ${artifactId}
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848