server:
  port: 8761

#配置身份验证，和url的账号密码保持一致
spring:
  security:
    user:
      name: sample #账号
      password: sample123 #密码

eureka:
  environment: pro
  client:
    register-with-eureka: false # 当前服务不需要到eureka server上注册为客户端
    fetch-registry: false # 是否检索服务
    service-url: # eureka服务地址
#      defaultZone: http://localhost:8761/eureka #不需要账号密码访问
      defaultZone: http://sample:sample123@localhost:8761/eureka #需要账号密码访问
  # 关闭eureka自我保护机制，心跳间隔设置短点，超时即剔除服务
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
