server:
  port: 8761

#配置身份验证，和url的账号密码保持一致
spring:
  security:
    user:
      name: techfish #账号
      password: techfish123 #密码

eureka:
  environment: pro
  client:
    register-with-eureka: false # 当前服务不需要到eureka server上注册为客户端
    fetch-registry: false # 是否检索服务
    service-url: # eureka服务地址
#      defaultZone: http://localhost:8761/eureka #不需要账号密码访问
      defaultZone: http://techfish:techfish123@localhost:8761/eureka #需要账号密码访问
