server:
  port: 10091

spring:
  application:
    name: ${artifactId}
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${artifactId}

management:
  endpoints:
    web:
      exposure:
        include: "*"