server:
  port: 8763

spring:
  application:
    name: cloud-eureka-ha
  security:
    user:
      name: sample
      password: sample123

eureka:
  client:
    service-url:
      defaultZone: http://sample:sample123@localhost:8761/eureka,http://sample:sample123@localhost:8762/eureka
