server:
  port: 8763

spring:
  application:
    name: cloud-eureka-ha
  security:
    user:
      name: techfish
      password: techfish123

eureka:
  client:
    service-url:
      defaultZone: http://techfish:techfish123@localhost:8761/eureka,http://techfish:techfish123@localhost:8762/eureka
