server:
  port: 10093

spring:
  application:
    name: ${artifactId}
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          input1:
            consumer:
              orderly: true
          input2:
            consumer:
              orderly: false
      bindings:
        input1:
          content-type: application/json
          destination: test-topic1
          group: test-group1
        input2:
          consumer:
            maxAttempts: 1
          content-type: application/json
          destination: test-topic2
          group: test-group2
