apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: test-order
  name: test-order
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: "10091"
      port: 10091
      targetPort: 10091
    - name: "12000"
      port: 12000
      targetPort: 12000
  selector:
    io.kompose.service: test-order
  type: LoadBalancer
status:
  loadBalancer: {}
