apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    sample.service: test-order
  name: test-order
spec:
  replicas: 1
  selector:
    matchLabels:
      sample.service: test-order
      logging: fluentd
  strategy: {}
  template:
    metadata:
      labels:
        sample.service: test-order
        logging: fluentd
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Shanghai
          image: 192.168.1.222:5000/cnte-test/test-order:2.1
          name: test-order
          ports:
            - containerPort: 10091
            - containerPort: 12000
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 12000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 12000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources: {}
      terminationGracePeriodSeconds: 60  
      restartPolicy: Always
status: {}
