dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.cn.test.cloud.user.service.dubbo.service
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost

spring:
  application:
    # Dubbo 应用名称
    name: ${artifactId}
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848