user:
  age: 15

ribbon:
  # 饥饿加载
  eager-load:
    enabled: true
    # 声明需要饥饿加载的服务
    clients:
    - cloud-user-service-nacos

management:
  metrics:
    tags:
      application: ${artifactId}
    enable:
      # 自定义哪些metrice不暴露，已暴露哪些可以从/actuator/metrics查看
      jvm: false
  endpoints:
    web:
      exposure:
        include: '*'