user:
  age: 15

ribbon:
  # 饥饿加载
  eager-load:
    enabled: true
    # 声明需要饥饿加载的服务
    clients:
    - cloud-user-service-nacos

management:
  metrics:
    tags:
      application: ${artifactId}
    enable:
      # 自定义哪些metrice不暴露，已暴露哪些可以从/actuator/metrics查看
      jvm: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_sample?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: chennan
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1

mybatis:
  typeAliasesPackage: com.cn.test.cloud.common.model.po
  mapperLocations: classpath:com/cn/test/cloud/commom/dal/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true